version: '3.4'
services:
  open-api-generator:
    image: semtech/mu-cl-resources-openapi-generator
    volumes:
      - ./config/resources:/config
      - ./data/nginx/api-doc-data:/config/output
      - ./config/open-api-generator:/config/start-container
    entrypoint:
      - bash
      - "/config/start-container/generate-api-doc.sh"
    depends_on:
      - database
  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      - "API_URL=/api-doc-data/openapi.json"
      - "PORT=80"
  nginx:
    image: nginx
    volumes:
      - ./data/nginx:/usr/share/nginx/html:ro
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - identifier:backend
      - swagger:swagger
    depends_on:
      - swagger
      - identifier
  identifier:
    image: semtech/mu-identifier:1.3.0
  dispatcher:
    image: semtech/mu-dispatcher:1.1.0
    volumes:
      - ./config/dispatcher:/config
  database:
    image: tenforce/virtuoso:1.3.0-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources:1.16.0
    volumes:
      - ./config/resources:/config
